export type IconName =
  | 'add-active'
  | 'add'
  | 'alert'
  | 'arrow-down'
  | 'arrow-key-down'
  | 'arrow-key-down'
  | 'arrow-key-left'
  | 'arrow-key-left'
  | 'arrow-key-right'
  | 'arrow-key-right'
  | 'arrow-key-up'
  | 'arrow-key-up'
  | 'arrow-up'
  | 'atlas-zoom-in'
  | 'atlas-zoom-in'
  | 'atlas-zoom-out'
  | 'atlas-zoom-out'
  | 'camera'
  | 'camera'
  | 'center-camera'
  | 'center-camera'
  | 'chevron-right'
  | 'close'
  | 'cloud-upload'
  | 'delete'
  | 'duplicate'
  | 'edit-active'
  | 'edit-active'
  | 'edit'
  | 'edit'
  | 'ellipsis'
  | 'export'
  | 'export'
  | 'facebook'
  | 'geometries'
  | 'geometries'
  | 'grid-active'
  | 'grid'
  | 'heart-full'
  | 'heart'
  | 'import'
  | 'import'
  | 'list-active'
  | 'list'
  | 'locate-land'
  | 'locate-land'
  | 'minus'
  | 'modal-back'
  | 'modal-back'
  | 'modal-close'
  | 'modal-close'
  | 'move-active'
  | 'move'
  | 'pin'
  | 'pin-active'
  | 'plus'
  | 'preview-active'
  | 'preview'
  | 'rotate-active'
  | 'rotate-left'
  | 'rotate-left'
  | 'rotate-right'
  | 'rotate-right'
  | 'rotate'
  | 'scale'
  | 'scene-object'
  | 'scene-parcel'
  | 'share'
  | 'shortcuts'
  | 'sidebar-active'
  | 'sidebar'
  | 'smart'
  | 'table'
  | 'table-active'
  | 'textures'
  | 'triangles'
  | 'twitter'
  | 'undo'
  | 'view'
  | 'zoom-in'
  | 'zoom-out'

export type DefaultProps = {
  isActive: boolean
  className: string
}

export type Props = DefaultProps & {
  name: IconName
  onClick?: (event: React.MouseEvent<HTMLElement>) => any
}

export type MapStateProps = Pick<Props, 'name'>
export type MapDispatchProps = {}
