/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import { UnsignedTransaction } from "ethers/utils/transaction";
import { TypedEventDescription, TypedFunctionDescription } from ".";

interface ENSInterface extends Interface {
  functions: {
    resolver: TypedFunctionDescription<{ encode([node]: [Arrayish]): string }>;

    owner: TypedFunctionDescription<{ encode([node]: [Arrayish]): string }>;

    setSubnodeOwner: TypedFunctionDescription<{
      encode([node, label, owner]: [Arrayish, Arrayish, string]): string;
    }>;

    setTTL: TypedFunctionDescription<{
      encode([node, ttl]: [Arrayish, BigNumberish]): string;
    }>;

    ttl: TypedFunctionDescription<{ encode([node]: [Arrayish]): string }>;

    setResolver: TypedFunctionDescription<{
      encode([node, resolver]: [Arrayish, string]): string;
    }>;

    setOwner: TypedFunctionDescription<{
      encode([node, owner]: [Arrayish, string]): string;
    }>;
  };

  events: {
    Transfer: TypedEventDescription<{
      encodeTopics([node, owner]: [Arrayish | null, null]): string[];
    }>;

    NewOwner: TypedEventDescription<{
      encodeTopics([node, label, owner]: [
        Arrayish | null,
        Arrayish | null,
        null
      ]): string[];
    }>;

    NewResolver: TypedEventDescription<{
      encodeTopics([node, resolver]: [Arrayish | null, null]): string[];
    }>;

    NewTTL: TypedEventDescription<{
      encodeTopics([node, ttl]: [Arrayish | null, null]): string[];
    }>;
  };
}

export class ENS extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ENS;
  attach(addressOrName: string): ENS;
  deployed(): Promise<ENS>;

  on(event: EventFilter | string, listener: Listener): ENS;
  once(event: EventFilter | string, listener: Listener): ENS;
  addListener(eventName: EventFilter | string, listener: Listener): ENS;
  removeAllListeners(eventName: EventFilter | string): ENS;
  removeListener(eventName: any, listener: Listener): ENS;

  interface: ENSInterface;

  functions: {
    resolver(node: Arrayish, overrides?: UnsignedTransaction): Promise<string>;

    "resolver(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    owner(node: Arrayish, overrides?: UnsignedTransaction): Promise<string>;

    "owner(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    setSubnodeOwner(
      node: Arrayish,
      label: Arrayish,
      owner: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setSubnodeOwner(bytes32,bytes32,address)"(
      node: Arrayish,
      label: Arrayish,
      owner: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    setTTL(
      node: Arrayish,
      ttl: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setTTL(bytes32,uint64)"(
      node: Arrayish,
      ttl: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    ttl(node: Arrayish, overrides?: UnsignedTransaction): Promise<BigNumber>;

    "ttl(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setResolver(
      node: Arrayish,
      resolver: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setResolver(bytes32,address)"(
      node: Arrayish,
      resolver: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    setOwner(
      node: Arrayish,
      owner: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setOwner(bytes32,address)"(
      node: Arrayish,
      owner: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;
  };

  resolver(node: Arrayish, overrides?: UnsignedTransaction): Promise<string>;

  "resolver(bytes32)"(
    node: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<string>;

  owner(node: Arrayish, overrides?: UnsignedTransaction): Promise<string>;

  "owner(bytes32)"(
    node: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<string>;

  setSubnodeOwner(
    node: Arrayish,
    label: Arrayish,
    owner: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setSubnodeOwner(bytes32,bytes32,address)"(
    node: Arrayish,
    label: Arrayish,
    owner: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  setTTL(
    node: Arrayish,
    ttl: BigNumberish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setTTL(bytes32,uint64)"(
    node: Arrayish,
    ttl: BigNumberish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  ttl(node: Arrayish, overrides?: UnsignedTransaction): Promise<BigNumber>;

  "ttl(bytes32)"(
    node: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<BigNumber>;

  setResolver(
    node: Arrayish,
    resolver: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setResolver(bytes32,address)"(
    node: Arrayish,
    resolver: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  setOwner(
    node: Arrayish,
    owner: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setOwner(bytes32,address)"(
    node: Arrayish,
    owner: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  filters: {
    Transfer(node: Arrayish | null, owner: null): EventFilter;

    NewOwner(
      node: Arrayish | null,
      label: Arrayish | null,
      owner: null
    ): EventFilter;

    NewResolver(node: Arrayish | null, resolver: null): EventFilter;

    NewTTL(node: Arrayish | null, ttl: null): EventFilter;
  };

  estimate: {
    resolver(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "resolver(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    owner(node: Arrayish, overrides?: UnsignedTransaction): Promise<BigNumber>;

    "owner(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setSubnodeOwner(
      node: Arrayish,
      label: Arrayish,
      owner: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setSubnodeOwner(bytes32,bytes32,address)"(
      node: Arrayish,
      label: Arrayish,
      owner: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setTTL(
      node: Arrayish,
      ttl: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setTTL(bytes32,uint64)"(
      node: Arrayish,
      ttl: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    ttl(node: Arrayish, overrides?: UnsignedTransaction): Promise<BigNumber>;

    "ttl(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setResolver(
      node: Arrayish,
      resolver: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setResolver(bytes32,address)"(
      node: Arrayish,
      resolver: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setOwner(
      node: Arrayish,
      owner: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setOwner(bytes32,address)"(
      node: Arrayish,
      owner: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;
  };
}
