/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import { UnsignedTransaction } from "ethers/utils/transaction";
import { TypedEventDescription, TypedFunctionDescription } from ".";

interface ENSResolverInterface extends Interface {
  functions: {
    supportsInterface: TypedFunctionDescription<{
      encode([interfaceID]: [Arrayish]): string;
    }>;

    setDNSRecords: TypedFunctionDescription<{
      encode([node, data]: [Arrayish, Arrayish]): string;
    }>;

    setText: TypedFunctionDescription<{
      encode([node, key, value]: [Arrayish, string, string]): string;
    }>;

    interfaceImplementer: TypedFunctionDescription<{
      encode([node, interfaceID]: [Arrayish, Arrayish]): string;
    }>;

    ABI: TypedFunctionDescription<{
      encode([node, contentTypes]: [Arrayish, BigNumberish]): string;
    }>;

    setPubkey: TypedFunctionDescription<{
      encode([node, x, y]: [Arrayish, Arrayish, Arrayish]): string;
    }>;

    setContenthash: TypedFunctionDescription<{
      encode([node, hash]: [Arrayish, Arrayish]): string;
    }>;

    addr: TypedFunctionDescription<{ encode([node]: [Arrayish]): string }>;

    setAuthorisation: TypedFunctionDescription<{
      encode([node, target, isAuthorised]: [Arrayish, string, boolean]): string;
    }>;

    hasDNSRecords: TypedFunctionDescription<{
      encode([node, name]: [Arrayish, Arrayish]): string;
    }>;

    text: TypedFunctionDescription<{
      encode([node, key]: [Arrayish, string]): string;
    }>;

    setABI: TypedFunctionDescription<{
      encode([node, contentType, data]: [
        Arrayish,
        BigNumberish,
        Arrayish
      ]): string;
    }>;

    name: TypedFunctionDescription<{ encode([node]: [Arrayish]): string }>;

    setName: TypedFunctionDescription<{
      encode([node, name]: [Arrayish, string]): string;
    }>;

    setAddr: TypedFunctionDescription<{
      encode([node, coinType, a]: [Arrayish, BigNumberish, Arrayish]): string;
    }>;

    dnsRecord: TypedFunctionDescription<{
      encode([node, name, resource]: [
        Arrayish,
        Arrayish,
        BigNumberish
      ]): string;
    }>;

    clearDNSZone: TypedFunctionDescription<{
      encode([node]: [Arrayish]): string;
    }>;

    contenthash: TypedFunctionDescription<{
      encode([node]: [Arrayish]): string;
    }>;

    pubkey: TypedFunctionDescription<{ encode([node]: [Arrayish]): string }>;

    setInterface: TypedFunctionDescription<{
      encode([node, interfaceID, implementer]: [
        Arrayish,
        Arrayish,
        string
      ]): string;
    }>;

    authorisations: TypedFunctionDescription<{
      encode([, ,]: [Arrayish, string, string]): string;
    }>;
  };

  events: {
    AuthorisationChanged: TypedEventDescription<{
      encodeTopics([node, owner, target, isAuthorised]: [
        Arrayish | null,
        string | null,
        string | null,
        null
      ]): string[];
    }>;

    TextChanged: TypedEventDescription<{
      encodeTopics([node, indexedKey, key]: [
        Arrayish | null,
        string | null,
        null
      ]): string[];
    }>;

    PubkeyChanged: TypedEventDescription<{
      encodeTopics([node, x, y]: [Arrayish | null, null, null]): string[];
    }>;

    NameChanged: TypedEventDescription<{
      encodeTopics([node, name]: [Arrayish | null, null]): string[];
    }>;

    InterfaceChanged: TypedEventDescription<{
      encodeTopics([node, interfaceID, implementer]: [
        Arrayish | null,
        Arrayish | null,
        null
      ]): string[];
    }>;

    DNSRecordChanged: TypedEventDescription<{
      encodeTopics([node, name, resource, record]: [
        Arrayish | null,
        null,
        null,
        null
      ]): string[];
    }>;

    DNSRecordDeleted: TypedEventDescription<{
      encodeTopics([node, name, resource]: [
        Arrayish | null,
        null,
        null
      ]): string[];
    }>;

    DNSZoneCleared: TypedEventDescription<{
      encodeTopics([node]: [Arrayish | null]): string[];
    }>;

    ContenthashChanged: TypedEventDescription<{
      encodeTopics([node, hash]: [Arrayish | null, null]): string[];
    }>;

    AddrChanged: TypedEventDescription<{
      encodeTopics([node, a]: [Arrayish | null, null]): string[];
    }>;

    AddressChanged: TypedEventDescription<{
      encodeTopics([node, coinType, newAddress]: [
        Arrayish | null,
        null,
        null
      ]): string[];
    }>;

    ABIChanged: TypedEventDescription<{
      encodeTopics([node, contentType]: [
        Arrayish | null,
        BigNumberish | null
      ]): string[];
    }>;
  };
}

export class ENSResolver extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ENSResolver;
  attach(addressOrName: string): ENSResolver;
  deployed(): Promise<ENSResolver>;

  on(event: EventFilter | string, listener: Listener): ENSResolver;
  once(event: EventFilter | string, listener: Listener): ENSResolver;
  addListener(eventName: EventFilter | string, listener: Listener): ENSResolver;
  removeAllListeners(eventName: EventFilter | string): ENSResolver;
  removeListener(eventName: any, listener: Listener): ENSResolver;

  interface: ENSResolverInterface;

  functions: {
    supportsInterface(
      interfaceID: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    "supportsInterface(bytes4)"(
      interfaceID: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    setDNSRecords(
      node: Arrayish,
      data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setDNSRecords(bytes32,bytes)"(
      node: Arrayish,
      data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    setText(
      node: Arrayish,
      key: string,
      value: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setText(bytes32,string,string)"(
      node: Arrayish,
      key: string,
      value: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    interfaceImplementer(
      node: Arrayish,
      interfaceID: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    "interfaceImplementer(bytes32,bytes4)"(
      node: Arrayish,
      interfaceID: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    ABI(
      node: Arrayish,
      contentTypes: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<[BigNumber, string]>;

    "ABI(bytes32,uint256)"(
      node: Arrayish,
      contentTypes: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<[BigNumber, string]>;

    setPubkey(
      node: Arrayish,
      x: Arrayish,
      y: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setPubkey(bytes32,bytes32,bytes32)"(
      node: Arrayish,
      x: Arrayish,
      y: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    setContenthash(
      node: Arrayish,
      hash: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setContenthash(bytes32,bytes)"(
      node: Arrayish,
      hash: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    addr(node: Arrayish, overrides?: UnsignedTransaction): Promise<string>;

    "addr(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    "addr(bytes32,uint256)"(
      node: Arrayish,
      coinType: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    setAuthorisation(
      node: Arrayish,
      target: string,
      isAuthorised: boolean,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setAuthorisation(bytes32,address,bool)"(
      node: Arrayish,
      target: string,
      isAuthorised: boolean,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    hasDNSRecords(
      node: Arrayish,
      name: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    "hasDNSRecords(bytes32,bytes32)"(
      node: Arrayish,
      name: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    text(
      node: Arrayish,
      key: string,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    "text(bytes32,string)"(
      node: Arrayish,
      key: string,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    setABI(
      node: Arrayish,
      contentType: BigNumberish,
      data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setABI(bytes32,uint256,bytes)"(
      node: Arrayish,
      contentType: BigNumberish,
      data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    name(node: Arrayish, overrides?: UnsignedTransaction): Promise<string>;

    "name(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    setName(
      node: Arrayish,
      name: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setName(bytes32,string)"(
      node: Arrayish,
      name: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    setAddr(
      node: Arrayish,
      coinType: BigNumberish,
      a: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setAddr(bytes32,uint256,bytes)"(
      node: Arrayish,
      coinType: BigNumberish,
      a: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setAddr(bytes32,address)"(
      node: Arrayish,
      a: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    dnsRecord(
      node: Arrayish,
      name: Arrayish,
      resource: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    "dnsRecord(bytes32,bytes32,uint16)"(
      node: Arrayish,
      name: Arrayish,
      resource: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    clearDNSZone(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "clearDNSZone(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    contenthash(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    "contenthash(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<string>;

    pubkey(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<[string, string] & { x: string; y: string }>;

    "pubkey(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<[string, string] & { x: string; y: string }>;

    setInterface(
      node: Arrayish,
      interfaceID: Arrayish,
      implementer: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    "setInterface(bytes32,bytes4,address)"(
      node: Arrayish,
      interfaceID: Arrayish,
      implementer: string,
      overrides?: UnsignedTransaction
    ): Promise<ContractTransaction>;

    authorisations(
      arg0: Arrayish,
      arg1: string,
      arg2: string,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    "authorisations(bytes32,address,address)"(
      arg0: Arrayish,
      arg1: string,
      arg2: string,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;
  };

  supportsInterface(
    interfaceID: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  "supportsInterface(bytes4)"(
    interfaceID: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  setDNSRecords(
    node: Arrayish,
    data: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setDNSRecords(bytes32,bytes)"(
    node: Arrayish,
    data: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  setText(
    node: Arrayish,
    key: string,
    value: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setText(bytes32,string,string)"(
    node: Arrayish,
    key: string,
    value: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  interfaceImplementer(
    node: Arrayish,
    interfaceID: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<string>;

  "interfaceImplementer(bytes32,bytes4)"(
    node: Arrayish,
    interfaceID: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<string>;

  ABI(
    node: Arrayish,
    contentTypes: BigNumberish,
    overrides?: UnsignedTransaction
  ): Promise<[BigNumber, string]>;

  "ABI(bytes32,uint256)"(
    node: Arrayish,
    contentTypes: BigNumberish,
    overrides?: UnsignedTransaction
  ): Promise<[BigNumber, string]>;

  setPubkey(
    node: Arrayish,
    x: Arrayish,
    y: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setPubkey(bytes32,bytes32,bytes32)"(
    node: Arrayish,
    x: Arrayish,
    y: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  setContenthash(
    node: Arrayish,
    hash: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setContenthash(bytes32,bytes)"(
    node: Arrayish,
    hash: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  addr(node: Arrayish, overrides?: UnsignedTransaction): Promise<string>;

  "addr(bytes32)"(
    node: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<string>;

  "addr(bytes32,uint256)"(
    node: Arrayish,
    coinType: BigNumberish,
    overrides?: UnsignedTransaction
  ): Promise<string>;

  setAuthorisation(
    node: Arrayish,
    target: string,
    isAuthorised: boolean,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setAuthorisation(bytes32,address,bool)"(
    node: Arrayish,
    target: string,
    isAuthorised: boolean,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  hasDNSRecords(
    node: Arrayish,
    name: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  "hasDNSRecords(bytes32,bytes32)"(
    node: Arrayish,
    name: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  text(
    node: Arrayish,
    key: string,
    overrides?: UnsignedTransaction
  ): Promise<string>;

  "text(bytes32,string)"(
    node: Arrayish,
    key: string,
    overrides?: UnsignedTransaction
  ): Promise<string>;

  setABI(
    node: Arrayish,
    contentType: BigNumberish,
    data: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setABI(bytes32,uint256,bytes)"(
    node: Arrayish,
    contentType: BigNumberish,
    data: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  name(node: Arrayish, overrides?: UnsignedTransaction): Promise<string>;

  "name(bytes32)"(
    node: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<string>;

  setName(
    node: Arrayish,
    name: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setName(bytes32,string)"(
    node: Arrayish,
    name: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  setAddr(
    node: Arrayish,
    coinType: BigNumberish,
    a: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setAddr(bytes32,uint256,bytes)"(
    node: Arrayish,
    coinType: BigNumberish,
    a: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setAddr(bytes32,address)"(
    node: Arrayish,
    a: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  dnsRecord(
    node: Arrayish,
    name: Arrayish,
    resource: BigNumberish,
    overrides?: UnsignedTransaction
  ): Promise<string>;

  "dnsRecord(bytes32,bytes32,uint16)"(
    node: Arrayish,
    name: Arrayish,
    resource: BigNumberish,
    overrides?: UnsignedTransaction
  ): Promise<string>;

  clearDNSZone(
    node: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "clearDNSZone(bytes32)"(
    node: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  contenthash(node: Arrayish, overrides?: UnsignedTransaction): Promise<string>;

  "contenthash(bytes32)"(
    node: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<string>;

  pubkey(
    node: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<[string, string] & { x: string; y: string }>;

  "pubkey(bytes32)"(
    node: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<[string, string] & { x: string; y: string }>;

  setInterface(
    node: Arrayish,
    interfaceID: Arrayish,
    implementer: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  "setInterface(bytes32,bytes4,address)"(
    node: Arrayish,
    interfaceID: Arrayish,
    implementer: string,
    overrides?: UnsignedTransaction
  ): Promise<ContractTransaction>;

  authorisations(
    arg0: Arrayish,
    arg1: string,
    arg2: string,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  "authorisations(bytes32,address,address)"(
    arg0: Arrayish,
    arg1: string,
    arg2: string,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  filters: {
    AuthorisationChanged(
      node: Arrayish | null,
      owner: string | null,
      target: string | null,
      isAuthorised: null
    ): EventFilter;

    TextChanged(
      node: Arrayish | null,
      indexedKey: string | null,
      key: null
    ): EventFilter;

    PubkeyChanged(node: Arrayish | null, x: null, y: null): EventFilter;

    NameChanged(node: Arrayish | null, name: null): EventFilter;

    InterfaceChanged(
      node: Arrayish | null,
      interfaceID: Arrayish | null,
      implementer: null
    ): EventFilter;

    DNSRecordChanged(
      node: Arrayish | null,
      name: null,
      resource: null,
      record: null
    ): EventFilter;

    DNSRecordDeleted(
      node: Arrayish | null,
      name: null,
      resource: null
    ): EventFilter;

    DNSZoneCleared(node: Arrayish | null): EventFilter;

    ContenthashChanged(node: Arrayish | null, hash: null): EventFilter;

    AddrChanged(node: Arrayish | null, a: null): EventFilter;

    AddressChanged(
      node: Arrayish | null,
      coinType: null,
      newAddress: null
    ): EventFilter;

    ABIChanged(
      node: Arrayish | null,
      contentType: BigNumberish | null
    ): EventFilter;
  };

  estimate: {
    supportsInterface(
      interfaceID: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "supportsInterface(bytes4)"(
      interfaceID: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setDNSRecords(
      node: Arrayish,
      data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setDNSRecords(bytes32,bytes)"(
      node: Arrayish,
      data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setText(
      node: Arrayish,
      key: string,
      value: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setText(bytes32,string,string)"(
      node: Arrayish,
      key: string,
      value: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    interfaceImplementer(
      node: Arrayish,
      interfaceID: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "interfaceImplementer(bytes32,bytes4)"(
      node: Arrayish,
      interfaceID: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    ABI(
      node: Arrayish,
      contentTypes: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "ABI(bytes32,uint256)"(
      node: Arrayish,
      contentTypes: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setPubkey(
      node: Arrayish,
      x: Arrayish,
      y: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setPubkey(bytes32,bytes32,bytes32)"(
      node: Arrayish,
      x: Arrayish,
      y: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setContenthash(
      node: Arrayish,
      hash: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setContenthash(bytes32,bytes)"(
      node: Arrayish,
      hash: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    addr(node: Arrayish, overrides?: UnsignedTransaction): Promise<BigNumber>;

    "addr(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "addr(bytes32,uint256)"(
      node: Arrayish,
      coinType: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setAuthorisation(
      node: Arrayish,
      target: string,
      isAuthorised: boolean,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setAuthorisation(bytes32,address,bool)"(
      node: Arrayish,
      target: string,
      isAuthorised: boolean,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    hasDNSRecords(
      node: Arrayish,
      name: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "hasDNSRecords(bytes32,bytes32)"(
      node: Arrayish,
      name: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    text(
      node: Arrayish,
      key: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "text(bytes32,string)"(
      node: Arrayish,
      key: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setABI(
      node: Arrayish,
      contentType: BigNumberish,
      data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setABI(bytes32,uint256,bytes)"(
      node: Arrayish,
      contentType: BigNumberish,
      data: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    name(node: Arrayish, overrides?: UnsignedTransaction): Promise<BigNumber>;

    "name(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setName(
      node: Arrayish,
      name: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setName(bytes32,string)"(
      node: Arrayish,
      name: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setAddr(
      node: Arrayish,
      coinType: BigNumberish,
      a: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setAddr(bytes32,uint256,bytes)"(
      node: Arrayish,
      coinType: BigNumberish,
      a: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setAddr(bytes32,address)"(
      node: Arrayish,
      a: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    dnsRecord(
      node: Arrayish,
      name: Arrayish,
      resource: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "dnsRecord(bytes32,bytes32,uint16)"(
      node: Arrayish,
      name: Arrayish,
      resource: BigNumberish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    clearDNSZone(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "clearDNSZone(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    contenthash(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "contenthash(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    pubkey(node: Arrayish, overrides?: UnsignedTransaction): Promise<BigNumber>;

    "pubkey(bytes32)"(
      node: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    setInterface(
      node: Arrayish,
      interfaceID: Arrayish,
      implementer: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "setInterface(bytes32,bytes4,address)"(
      node: Arrayish,
      interfaceID: Arrayish,
      implementer: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    authorisations(
      arg0: Arrayish,
      arg1: string,
      arg2: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "authorisations(bytes32,address,address)"(
      arg0: Arrayish,
      arg1: string,
      arg2: string,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;
  };
}
